# Generated by Django 4.0.6 on 2022-07-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickever', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='title',
            new_name='Subject',
        ),
    ]
