# Generated by Django 4.0.6 on 2022-07-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickever', '0002_rename_title_music_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Subject',
            new_name='title',
        ),
    ]
